import { join } from "node:path";

export {};

const project_name = "ikyo"

const arg1 = Deno.args[0] ?? "config"  // config or build
const arg2 = Deno.args[1] ?? "debug"   // debug or release

const dirs = ["main"]

const msvc_flag: string[] = []
const clang_flag = ["-std=c++20", "-Wall", "-Wextra",]

const msvc_debug_flag: string[] = []
const msvc_release_flag: string[] = []

const clang_debug_flag =   ["-g", "-O0", "-ffast-math", "-DDEBUG"]
const clang_release_flag = ["-03", "-ffast-math", "-DNDEBUG"]

const source_files: string[] = []
for (const dir of dirs) {
  const bfile = join(".", "src", dir, ".b")
  try {
    const text = await Deno.readTextFile(bfile)
    const lines = text.split('\n').filter(line => line.trim() !== '')
    lines.forEach(line => {
      const parts = line.split('/')
      source_files.push(join(".", "src", dir, ...parts))
    })
  } catch (e) {
    if (e instanceof Deno.errors.NotFound) {
      console.log(`${bfile} 파일이 존재하지 않습니다`)
    } else {
      console.log(`${bfile} 읽기 실패:`)
    }
  }
}

// Platform detection
const os_map: Record<string, string> = {
  "darwin": "macos",
  "linux": "linux",
  "windows": "windows"
}

const arch_map: Record<string, string> = {
  "x86_64": "x64",
  "aarch64": "arm64"
}

const os = os_map[Deno.build.os] ?? Deno.build.os
const arch = arch_map[Deno.build.arch] ?? Deno.build.arch
const mode = arg2  // "debug" or "release"

// Triplet: {os}-{arch}-{mode}
const triplet = `${os}-${arch}-${mode}`

// Output directories
const out_dir = join("out", triplet)
const obj_dir = join(out_dir, "obj")
const bin_dir = join(out_dir, "bin")

// Compiler setup
const is_windows = Deno.build.os === "windows"
const compiler = is_windows ? "cl.exe" : "clang++"
const obj_ext = is_windows ? ".obj" : ".o"
const exe_ext = is_windows ? ".exe" : ""

// Compiler flags
const cxx_flags = is_windows ? msvc_flag : clang_flag
const mode_flags = mode === "debug"
  ? (is_windows ? msvc_debug_flag : clang_debug_flag)
  : (is_windows ? msvc_release_flag : clang_release_flag)

const all_flags = [...cxx_flags, ...mode_flags]

// Include directories
const include_flag = is_windows ? "/Isrc" : "-Isrc"

console.log("========================================")
console.log("IKYO Build System")
console.log("========================================")
console.log(`Mode: ${mode}`)
console.log(`Platform: ${os}`)
console.log(`Architecture: ${arch}`)
console.log(`Triplet: ${triplet}`)
console.log(`Compiler: ${compiler}`)
console.log("========================================\n")

console.log("Source files:")
for (const src of source_files) {
  console.log(`  - ${src}`)
}
console.log("")

// Create output directories
await Deno.mkdir(obj_dir, { recursive: true })
await Deno.mkdir(bin_dir, { recursive: true })

if (arg1 === "config") {
  // Generate compile_commands.json
  const compile_commands = source_files.map(src => ({
    directory: Deno.cwd(),
    command: `${compiler} ${all_flags.join(" ")} ${include_flag} -c ${src}`,
    file: src
  }))

  await Deno.writeTextFile(
    "compile_commands.json",
    JSON.stringify(compile_commands, null, 2)
  )

  console.log("Generated compile_commands.json")
} else {
  // Generate and run Ninja build
  const ninja_file = join(out_dir, "build.ninja")

  let ninja_content = "# Generated by IKYO Build System (Deno)\n"
  ninja_content += `# Triplet: ${triplet}\n\n`
  ninja_content += "ninja_required_version = 1.3\n\n"
  ninja_content += `cxx = ${compiler}\n`
  ninja_content += `cxx_flags = ${all_flags.join(" ")} ${include_flag}\n\n`

  // Compilation rule
  if (is_windows) {
    ninja_content += "rule cxx\n"
    ninja_content += "  command = $cxx /showIncludes $cxx_flags /c $in /Fo$out\n"
    ninja_content += "  deps = msvc\n"
    ninja_content += "  description = Compiling $in\n\n"

    ninja_content += "rule link\n"
    ninja_content += "  command = $cxx $in /Fe$out\n"
    ninja_content += "  description = Linking $out\n\n"
  } else {
    ninja_content += "rule cxx\n"
    ninja_content += "  command = $cxx -MMD -MF $out.d $cxx_flags -c $in -o $out\n"
    ninja_content += "  depfile = $out.d\n"
    ninja_content += "  deps = gcc\n"
    ninja_content += "  description = Compiling $in\n\n"

    ninja_content += "rule link\n"
    ninja_content += "  command = $cxx $in -o $out\n"
    ninja_content += "  description = Linking $out\n\n"
  }

  // Build edges for each source file
  const objects = []
  for (const source of source_files) {
    const obj_name = source.replace(/\.cc$/, obj_ext).replace(/[\/\.]/g, "_")
    const obj_path = join("obj", obj_name)
    // Use relative path from out_dir
    const source_rel = join("..", "..", source)

    ninja_content += `build ${obj_path}: cxx ${source_rel}\n`
    objects.push(obj_path)
  }

  ninja_content += "\n"

  // Link binary
  const binary_name = join("bin", project_name + exe_ext)
  ninja_content += `build ${binary_name}: link ${objects.join(" ")}\n\n`

  // Default target
  ninja_content += `default ${binary_name}\n`

  await Deno.writeTextFile(ninja_file, ninja_content)
  console.log(`Generated Ninja build file: ${ninja_file}\n`)

  // Run Ninja
  console.log(`Building ${triplet}...`)
  const cmd = new Deno.Command("ninja", {
    args: ["-f", "build.ninja"],
    cwd: out_dir,
    stdout: "inherit",
    stderr: "inherit"
  })

  const { success } = await cmd.output()

  if (success) {
    console.log("\nBuild successful!")
    console.log(`Binary: ${join(out_dir, binary_name)}`)
  } else {
    console.log("\nBuild failed!")
    Deno.exit(1)
  }
}
